### ISSUE TITLE
Port WinBond OTP driver into u-boot

### ISSUE THREAD

**Issue by abhijit-mahajani-imgtec** [FlowM2M/u-boot#13] opened 2016-11-10 09:20 UTC
Port winbond OTP driver into u-boot so that it can read mac addresses from OTP and store into uEnv partition i.e. uboot env variables such as ethaddr, wifiaddr, wifiapaddr, btaddr, lowpanaddr etc.

**Comment by Shpinkso** [comment] 2016-11-28 11:05
Duplicate of #19

**Closed as completed** 2016-11-28 11:05 UTC
